apiVersion: v1
kind: Service
metadata: 
    name: lembretes-service
spec:
    #Ip externo, acessível fora do cluster
    type: NodePort
    selector:
        #todo Pod que tiver esta tag
        #fará parte deste serviço
        app: lembretes
    ports:
      - name: lembretes
        protocol: TCP
        # o nó recebe requisições nessa porta
        port: 4000
        # e direciona para esta porta do Pod
        targetPort: 4000 